FROM node:14

RUN mkdir -p /Users/shipravalecha/Desktop/SeattleUniversity/SoftwareArch/processedImages
WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

CMD [ "node", "client.js" ]